# Copied from  git@github.com:palladius/clouddeploy-vertex-demo.git
################################################################################################
################################################################################################
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
description: My ♊️ Gemini 📰 News 🕷️ Crawler 🪈 Pipeline
metadata:
  name: gemini-news-crawler-rails-app
  description: |
    240331 v1.0 Copied from Demo Vegas24
    240331 v1.1 Removed automations as it still gives problems
serialPipeline:
  stages:
  - targetId: rails-dev
    profiles: [dev]
    strategy:
      standard:
        verify: true
  - targetId: rails-staging
    profiles: [staging]
    strategy:
      standard:
        verify: true
  - targetId: rails-prod
    profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: rails-dev
description: Cloud Run Dev service
run:
  location: projects/palladius-genai/locations/europe-west1
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
description: Cloud Run STAG service
metadata:
  name: rails-staging
run:
  location: projects/palladius-genai/locations/europe-west1

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: rails-prod
description: Cloud Run PROD service
#requireApproval: true
run:
  location: projects/palladius-genai/locations/europe-west1
---

# ---
# apiVersion: deploy.cloud.google.com/v1
# kind: Automation
# metadata:
#   name: gemini-news-crawler-rails-app/promote-dev2staging
# description: promotes a release Dev 2 staging immediately # after Deploy, Verify, PostDeploy
# suspended: false
# serviceAccount: 849075740253-compute@developer.gserviceaccount.com # correct ricc SA for ricc-and-nardy
# selector:
# - target:
#     id: rails-dev
# rules:
# - promoteRelease:
#     name: "promote-release-1to2"
#     wait: 0m
#     toTargetId: "@next"
# ---
# apiVersion: deploy.cloud.google.com/v1
# kind: Automation
# metadata:
#   name: gemini-news-crawler-rails-app/promote-staging2prod
# description: promotes a release staging 2 Prod immediately - pending approval
# suspended: false
# serviceAccount: 849075740253-compute@developer.gserviceaccount.com # correct ricc SA for ricc-and-nardy
# selector:
# - target:
#     id: rails-staging
# rules:
# - promoteRelease:
#     name: "promote-release-2to3"
#     wait: 0m
#     toTargetId: "@next"
