apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: deploy-rails-to-cloud-run
profiles:
- name: dev
  manifests:
    rawYaml:
    - deploy/run-service-dev.yaml
- name: staging
  manifests:
    rawYaml:
    - deploy/run-service-staging.yaml
- name: prod
  manifests:
    rawYaml:
    - deploy/run-service-prod.yaml
deploy:
#  cloudrun: {}
  cloudrun:
   region: europe-west1
